name: Test Compile
on: push
jobs:
  compile-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup build dir
        run: mkdir build

      - name: Compile and release
        uses: arduino/compile-sketches@v1.1.0
        with:
          platforms: |
            - source-url: "http://arduino.esp8266.com/stable/package_esp8266com_index.json"
              name: "esp8266:esp8266"
          fqbn: 'esp8266:esp8266:nodemcuv2'
          sketch-paths: |
            - "./tinet-bridge-esp8266.ino"
          librairies: |
            - name: ESP8266WiFi
            - name: ESP8266httpUpdate
            - name: ESP8266WebServer
          cli-compile-flags: |
            - -e

      - name: ls dirs
        run: ls && ls build && ls sketches-reports