name: Build And Release firmware.bin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Install platformIO libraries
        run: pio lib install

      - name: Run PlatformIO
        run: platformio run

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/nodemcuv2/firmware.bin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: .pio/build/nodemcuv2/firmware.bin
          tag_name: ${{ github.run_number }}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
